# Generated by Django 2.2 on 2019-04-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealcategory',
            old_name='departamentid',
            new_name='departmentid',
        ),
    ]
