# Generated by Django 2.2 on 2019-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190414_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='mealcategory',
            new_name='categoryid',
        ),
    ]
