# Generated by Django 2.2 on 2019-04-14 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190414_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='isitopen',
            field=models.BooleanField(default=True),
        ),
    ]
